
spring:
  # ===================================================================================================================================
  # Cache ??
  # ===================================================================================================================================
  cache:
    type: redis
  redis:
    host: ${server.host:localhost}  #??? ?? ???(default: localhost)
    port: 16379 #??? ?? ??(default: 6379)
  data:
    redis:
      repositories:
        enabled: false